import type { AppConfigDraft } from '../schema/config';
import { createDefaultLocalModelCapabilityRegistry } from '../utils/provider-model-capabilities';

export const appConfigDraftMock: AppConfigDraft = {
  activeProviderTemplateId: 'template-dashscope-realtime',
  providers: [{
    templateId: 'template-dashscope-realtime',
    templateVersion: '2026.05.10',
    templateSource: 'official',
    providerId: 'provider-dashscope',
    kind: 'dashscope',
    displayName: '阿里云百炼 API',
    mode: 'template',
    model: 'qwen3.5-omni-plus-realtime',
    baseUrl: 'https://dashscope.aliyuncs.com/api/v1',
    transport: 'websocket',
    authRef: {
      kind: 'credential-ref',
      reference: 'credential://provider/dashscope/default',
      headerName: 'Authorization',
      scheme: 'bearer',
    },
    region: 'cn-beijing',
    streamEnabled: true,
    timeoutMs: 12000,
    systemPromptTemplate: 'game-live-translation-cn',
    temperature: 0.2,
    maxOutputTokens: 256,
    responseModalities: ['text'],
    customHeaders: [],
    sceneModelAssignments: [
      {
        scenario: 'watch',
        modelIds: ['qwen3.5-livetranslate-flash-realtime'],
      },
      {
        scenario: 'game',
        modelIds: ['qwen3.5-omni-plus-realtime'],
      },
      {
        scenario: 'voice-room',
        modelIds: [],
      },
      {
        scenario: 'subtitle-translate',
        modelIds: [],
      },
    ],
    localModelCapabilityRegistry: createDefaultLocalModelCapabilityRegistry(),
    modelCatalogCache: {
      signature: '',
      source: 'preset',
      endpoint: null,
      fetchedAt: null,
      error: null,
      models: [],
    },
    probe: {
      profileId: 'probe-dashscope-baseline',
      verdict: 'realtime-risk',
      checkedAt: '2026-05-10T10:20:00+08:00',
      streamSupported: true,
      errorShapeStable: true,
      responseShapeStable: true,
    },
    status: 'draft',
  }],
  devices: {
    routeMode: 'watch',
    inputDeviceId: 'microphone-default',
    outputDeviceId: 'speaker-default',
    virtualRenderDeviceId: 'omni-virtual-speaker-default',
    playbackDeviceId: 'system-output-default',
    virtualMicState: 'pending',
    inboundRoute: {
      routeId: 'audio-route-inbound-watch',
      direction: 'inbound',
      input: {
        sourceId: 'system-output-default',
        kind: 'system-output',
        deviceId: 'system-output-default',
        state: 'capturing',
        muted: false,
        bufferAheadMs: 160,
        preBufferState: 'ready',
        processing: {
          inputLevel: 100,
          echoCancellationEnabled: false,
          noiseSuppressionEnabled: false,
          autoGainControlEnabled: false,
        },
      },
      outputs: [
        {
          targetId: 'subtitle-engine-default',
          kind: 'subtitle-engine',
          enabled: true,
        },
        {
          targetId: 'speaker-monitor-default',
          kind: 'speaker',
          deviceId: 'speaker-default',
          enabled: true,
        },
      ],
      mixControl: {
        keepOriginalAudio: true,
        translatedAudioEnabled: true,
        translatedAudioGainDb: 0,
        translatedAudioAutoGainEnabled: true,
        originalAudioGainDb: -4,
        duckingEnabled: true,
        duckingDepthPercent: 35,
        monitorMode: 'original-and-translated',
      },
      latencyControl: {
        captureBufferMs: 80,
        translationBufferMs: 120,
        playbackBufferMs: 40,
        compensationMs: 120,
      },
    },
    outboundRoute: {
      routeId: 'audio-route-outbound-mic',
      direction: 'outbound',
      input: {
        sourceId: 'microphone-default',
        kind: 'microphone',
        deviceId: 'microphone-default',
        state: 'armed',
        muted: false,
        bufferAheadMs: 60,
        preBufferState: 'primed',
        processing: {
          inputLevel: 100,
          echoCancellationEnabled: true,
          noiseSuppressionEnabled: true,
          autoGainControlEnabled: true,
        },
      },
      outputs: [
        {
          targetId: 'virtual-mic-default',
          kind: 'virtual-mic',
          deviceId: 'virtual-mic-default',
          enabled: false,
        },
        {
          targetId: 'speaker-local-monitor',
          kind: 'monitor',
          deviceId: 'speaker-default',
          enabled: true,
        },
      ],
      mixControl: {
        keepOriginalAudio: true,
        translatedAudioEnabled: true,
        translatedAudioGainDb: -1,
        translatedAudioAutoGainEnabled: false,
        originalAudioGainDb: -4,
        duckingEnabled: true,
        duckingDepthPercent: 45,
        monitorMode: 'original-and-translated',
      },
      latencyControl: {
        captureBufferMs: 50,
        translationBufferMs: 90,
        playbackBufferMs: 50,
        compensationMs: 110,
      },
      pushToTalk: {
        enabled: true,
        hotkey: 'Alt+V',
        state: 'armed',
        releaseDelayMs: 180,
      },
    },
    supportProfileId: 'support-watch-system-audio',
    inboundVoiceModelId: 'qwen3.5-livetranslate-flash-realtime',
    outboundVoiceModelId: 'qwen3.5-omni-plus-realtime',
    textToSpeechModelId: 'qwen3.5-omni-plus-realtime',
    subtitleTranslationMode: 'native',
    subtitleTranslationModelId: '',
    inboundSecondaryAudioModelId: '',
    inputLevel: 100,
    aecEnabled: true,
    ansEnabled: true,
    agcEnabled: true,
    outputLevel: 100,
    outputSpeechEnabled: true,
    outputSubtitlesEnabled: false,
    virtualMicOutputEnabled: true,
    feedbackLoopPrevention: 'echo-cancel',
    status: 'warning',
  },
  subtitles: {
    sourceLanguage: 'auto',
    targetLanguage: 'zh-CN',
    outboundTargetLanguage: '',
    translationLanguagePreference: 'zh-CN',
    mode: 'bilingual',
    captionDensity: 'balanced',
    priority: 'subtitle-first',
    instructions:
      '你是一个只输出译文的实时翻译引擎。把听到的所有内容（人声对话、旁白、歌词、视频与音乐中的人声等）直接翻译成中文。只输出译文，禁止任何解释、确认、寒暄或对音频本身的描述（如“我没听到有人说话”“只听到音乐”）。若确实没有可翻译的语言内容，保持静默，不输出任何文字。',
    overlayOpacity: 0.88,
    overlayLocked: false,
    overlayTextColor: '#fff8ef',
    overlayTextOpacity: 1,
    overlayTextAlign: 'center',
    overlaySourceTextStyle: {
      color: '#fff8ef',
      fontWeight: 500,
      outlineEnabled: true,
      outlineColor: '#000000',
      outlineWidth: 1,
      shadowEnabled: true,
      shadowColor: '#000000',
      shadowOpacity: 0.45,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      shadowBlur: 8,
    },
    overlayTranslationTextStyle: {
      color: '#fff8ef',
      fontWeight: 700,
      outlineEnabled: true,
      outlineColor: '#000000',
      outlineWidth: 1,
      shadowEnabled: true,
      shadowColor: '#000000',
      shadowOpacity: 0.4,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      shadowBlur: 8,
    },
    overlayBackgroundColor: '#111827',
    overlayBackgroundOpacity: 0.84,
    overlayFontFamily: '"Segoe UI", "Microsoft YaHei UI", sans-serif',
    overlayFontSize: 24,
    overlayWidth: 960,
    overlayHeight: 220,
    overlayX: 50,
    overlayY: 78,
    history: {
      enabled: true,
      sourceAudioEnabled: true,
      translatedAudioEnabled: true,
    },
    status: 'ready',
  },
  speech: {
    enabled: true,
    targetLanguage: 'zh-CN',
    voicePresetId: 'voice-cn-neutral',
    textToSpeechModelId: 'qwen3.5-omni-plus-realtime',
    voice: 'Ethan',
    outputTarget: 'virtual-mic',
    localPlaybackEnabled: true,
    virtualMicOutputEnabled: true,
    translationAudioSource: 'auto',
    dispatchState: 'waiting-subtitle',
    status: 'warning',
  },
  driver: {
    protocolVersion: '2026-08-27-audio-routing-v8',
    installChannel: 'development',
    installPhase: 'rollback-required',
    targetDeviceId: 'virtual-mic-default',
    expectedDriverVersion: '0.10.0-dev',
    expectedBridgeVersion: '0.1.0',
    bridgeState: 'degraded',
    driverHealth: 'version-mismatch',
    rollbackSupported: true,
    lastErrorCode: 'driver.version-mismatch',
    recommendedAction: 'rollback-driver',
    status: 'warning',
  },
  glossary: {
    templateId: 'glossary-template-watch',
    scenario: 'watch',
    injectionStrategy: 'scenario-first',
    injectionOrder: ['scenario-template', 'user-package', 'community-package'],
    activePackageIds: ['glossary-video-default'],
    communityPackageIds: ['community-anime-cn-v1'],
    gameDictionaryId: 'game-discord-default',
    importStrategy: 'merge',
    exportFormat: 'json',
    processingMode: 'inject-important',
    calibrationModelId: '',
    libraries: [],
    status: 'draft',
  },
  diagnostics: {
    installStatus: 'warning',
    driverStatus: 'warning',
    providerStatus: 'warning',
    deviceStatus: 'warning',
    lastExportScope: 'summary',
    supportTier: 'experimental',
    status: 'warning',
  },
  onboarding: {
    activePresetId: 'preset-watch-mode',
    completedStepIds: ['check-system-audio'],
    unresolvedRiskIds: ['risk-driver-bridge-not-ready', 'risk-provider-not-tested'],
    checklistStatus: 'warning',
  },
};
