import type { RuntimeNotification, RuntimeSnapshot } from '../schema/runtime-core';

export const browserPreviewRuntimeNotification: RuntimeNotification = {
  id: 'runtime-browser-preview',
  level: 'info',
  source: 'desktop-runtime',
  message: '当前运行在浏览器预览模式，Rust Core 命令桥会在 Tauri shell 中接管。',
  emittedAt: 'browser-preview',
};

export const runtimeSnapshotMock: RuntimeSnapshot = {
  coreState: 'ready',
  bridgeStatus: 'browser-preview',
  activeProfileId: 'desktop-shell-preview',
  trayReady: false,
  lastSyncAt: 'browser-preview',
  sessionId: 'browser-preview',
  bridge: {
    processStatus: 'stopped',
    installChannel: 'development',
    installPhase: 'planned',
    targetDeviceId: 'virtual-mic-default',
    virtualRenderDeviceId: 'omni-virtual-speaker-default',
    physicalPlaybackDeviceId: 'speaker-default',
    physicalPlaybackLevel: 100,
    mixControl: {
      keepOriginalAudio: true,
      translatedAudioEnabled: true,
      translatedAudioGainDb: 0,
      translatedAudioAutoGainEnabled: true,
      originalAudioGainDb: 0,
      duckingEnabled: true,
      duckingDepthPercent: 35,
      monitorMode: 'original-and-translated',
    },
    monitorPlaybackEnabled: true,
    expectedDriverVersion: '0.10.0-dev',
    expectedBridgeVersion: '0.1.0',
    bridgeState: 'stopped',
    lifecycleState: 'idle',
    driverHealth: 'not-installed',
    driverVersion: null,
    bridgeVersion: '0.1.0',
    captureBackend: 'wasapi-endpoint-loopback',
    captureLifecycleState: 'idle',
    captureRestartCount: 0,
    capturePacketCount: 0,
    captureFramesReceived: 0,
    capturePeak: 0,
    captureRms: 0,
    captureSilentPacketCount: 0,
    captureInvalidSampleCount: 0,
    resolvedPhysicalPlaybackDeviceId: '',
    monitorBufferedMs: 0,
    monitorUnderrunCount: 0,
    monitorOverrunCount: 0,
    queuedFrames: 0,
    sourceFramesCaptured: 0,
    translatedFramesAccepted: 0,
    playbackFramesWritten: 0,
    underrunCount: 0,
    droppedFrameCount: 0,
    driverBufferedBytes: 0,
    driverMaxBufferedBytes: 19200,
    driverCapturedBytes: 0,
    driverDeliveredBytes: 0,
    driverDroppedBytes: 0,
    sourcePendingBytes: 0,
    sourcePacerQueuedFrames: 0,
    monitorSourceQueuedFrames: 0,
    staleSourceFramesDropped: 0,
    sourceSubscriberActive: false,
    sourceGeneration: 0,
    sourceWorkerPhase: 'idle',
    sourceWorkerLastProgressTimestampMs: null,
    sourceReadCalls: 0,
    sourceZeroByteReads: 0,
    monitorPlaybackState: 'idle',
    lastFrameTimestampMs: null,
    lastErrorCode: 'driver.not-installed',
    recommendedAction: 'reinstall-driver',
    pipeName: 'omni-bridge-ipc',
    pipePath: '\\\\.\\pipe\\omni-bridge-ipc',
    audioPipePath: '\\\\.\\pipe\\omni-bridge-ipc-audio',
    sourcePipePath: '\\\\.\\pipe\\omni-bridge-ipc-source',
    runtimeRoot: 'browser-preview',
    sessionId: null,
    lastHandshakeAt: null,
    rollbackSupported: true,
    status: 'warning',
    driverProbeState: 'idle',
    testSigningEnabled: false,
    signatureEnforcementBypassed: false,
    memoryIntegrityEnabled: false,
    secureBootEnabled: null,
    secureBootProbeStatus: 'idle',
    rootDeviceCount: 0,
    rootInstanceIds: [],
    endpointName: null,
    abiVersion: null,
    ioctlAvailable: false,
    lastDriverOperation: null,
    driverDetail: null,
  },
  diagnostics: {
    status: 'preview',
    supportTier: 'experimental',
    installStatus: 'warning',
    providerStatus: 'warning',
    driverStatus: 'warning',
    deviceStatus: 'warning',
    lastSelfCheckAt: null,
    lastExportScope: null,
    lastExportPath: null,
    lastExportedAt: null,
    categories: [
      {
        category: 'runtime',
        filePath: 'browser-preview/runtime.log',
        entryCount: 1,
        lastEntryAt: 'browser-preview',
      },
      {
        category: 'bridge',
        filePath: 'browser-preview/bridge.log',
        entryCount: 1,
        lastEntryAt: 'browser-preview',
      },
    ],
    supportMatrix: [
      {
        id: 'provider-transport',
        label: '模型服务传输链路',
        status: 'warning',
        summary: '浏览器预览模式下不会执行真实模型服务探测。',
        recommendedAction: '在 Tauri Shell 中运行 diagnostics self-check。',
      },
      {
        id: 'driver-bridge',
        label: '驱动 / 桥接链路',
        status: 'warning',
        summary: '预览模式下不会连接 named pipe Bridge Service。',
        recommendedAction: '切换到桌面壳体验真实驱动状态。',
      },
    ],
    modelTraceSummary: {
      activeTraceId: null,
      totalCalls: 0,
      succeededCalls: 0,
      failedCalls: 0,
      lastError: null,
      lastCallAt: null,
      recentCalls: [],
    },
    recentLogs: [
      {
        id: 'browser-preview-runtime',
        category: 'runtime',
        level: 'info',
        summary: '当前运行在浏览器预览模式。',
        detail: 'Rust Core 命令桥会在 Tauri shell 中接管。',
        emittedAt: 'browser-preview',
        source: null,
        elapsedMs: null,
      },
    ],
    recentErrors: [],
    logDroppedCount: 0,
    logWriteErrorCount: 0,
  },
  storage: {
    status: 'preview',
    schemaVersion: 0,
    databasePath: 'browser-preview',
    credentialBackend: 'browser-preview',
    hasPersistedConfig: false,
    snapshotCount: 0,
    lastSavedAt: null,
    lastExportPath: null,
    lastImportPath: null,
  },
  windows: [
    {
      label: 'main',
      title: 'Omni Translate',
      kind: 'main',
      visible: true,
      focused: true,
    },
    {
      label: 'subtitle-overlay',
      title: '全语通译字幕浮窗',
      kind: 'subtitle-overlay',
      visible: false,
      focused: false,
    },
  ],
  notifications: [browserPreviewRuntimeNotification],
};
