use super::*;

pub(in crate::audio::omni) struct OmniSocketEventState<S: RealtimeSocket, R: tauri::Runtime = tauri::Wry> {
    pub(in crate::audio::omni) socket: S,
    pub(in crate::audio::omni) trace_call: crate::diagnostics::model_trace::ModelTraceCall<R>,
    pub(in crate::audio::omni) reconnect_count: usize,
    pub(in crate::audio::omni) pending_audio_buffer: Vec<i16>,
    pub(in crate::audio::omni) active_voice: String,
    pub(in crate::audio::omni) voice_fallback_applied: bool,
    pub(in crate::audio::omni) session_ready_for_audio: bool,
    pub(in crate::audio::omni) event_diagnostics: OmniEventDiagnostics,
    pub(in crate::audio::omni) current_cue_id: Option<String>,
    pub(in crate::audio::omni) pending_source_text: String,
    pub(in crate::audio::omni) pending_translated_text: String,
    pub(in crate::audio::omni) st_skip_logged: bool,
    pub(in crate::audio::omni) pending_audio_delta_count: u64,
    pub(in crate::audio::omni) pending_audio_delta_base64_bytes: u64,
    pub(in crate::audio::omni) pending_audio_response_id: Option<String>,
    pub(in crate::audio::omni) pending_audio_stream_cue_id: Option<String>,
    pub(in crate::audio::omni) pending_audio_stream_chunk_index: u32,
    pub(in crate::audio::omni) pending_audio_stream_created_at_ms: Option<u64>,
    pub(in crate::audio::omni) pending_audio_stream_aborted: bool,
    pub(in crate::audio::omni) last_vad_event_time: SystemTime,
    pub(in crate::audio::omni) vad_event_count: u64,
    pub(in crate::audio::omni) transcription_completed_flag: bool,
    pub(in crate::audio::omni) transcription_completed_at: Option<SystemTime>,
    pub(in crate::audio::omni) manual_response_pending: bool,
    pub(in crate::audio::omni) manual_response_requested: bool,
    pub(in crate::audio::omni) manual_response_item_id: Option<String>,
    pub(in crate::audio::omni) manual_response_released_at: Option<SystemTime>,
    pub(in crate::audio::omni) sent_audio_since_commit: bool,
    pub(in crate::audio::omni) audio_samples_since_commit: u64,
    pub(in crate::audio::omni) manual_turn_audio_after_response: bool,
}

pub(in crate::audio::omni) struct OmniSocketEventContext<'a, R: tauri::Runtime = tauri::Wry> {
    pub(in crate::audio::omni) app: &'a AppHandle<R>,
    pub(in crate::audio::omni) store: &'a AudioStateStore,
    pub(in crate::audio::omni) direction: &'a str,
    pub(in crate::audio::omni) session_generation: u64,
    pub(in crate::audio::omni) session_started_at: &'a SystemTime,
    pub(in crate::audio::omni) subtitle_translate_active: bool,
    pub(in crate::audio::omni) native_translation_reuse_active: bool,
    pub(in crate::audio::omni) total_input_chunks: u64,
    pub(in crate::audio::omni) first_audio_sent_ms: Option<u64>,
    pub(in crate::audio::omni) first_audible_chunk_ms: Option<u64>,
    pub(in crate::audio::omni) chunk_count: u64,
    pub(in crate::audio::omni) total_silence_skipped_before_first_audible: u64,
    pub(in crate::audio::omni) playback_tx: &'a OmniPlaybackQueue,
    pub(in crate::audio::omni) readiness_sent: &'a AtomicBool,
    pub(in crate::audio::omni) readiness_tx: &'a mpsc::Sender<Result<u64, String>>,
    pub(in crate::audio::omni) provider: &'a ProviderDraftInput,
    pub(in crate::audio::omni) provider_input_budget: &'a ProviderInputBudget,
    pub(in crate::audio::omni) instructions: &'a str,
    pub(in crate::audio::omni) glossary: &'a GlossaryContext,
    pub(in crate::audio::omni) audio_mode: RealtimeAudioMode,
    pub(in crate::audio::omni) output_mode: OmniOutputMode,
    pub(in crate::audio::omni) source_language: &'a str,
    pub(in crate::audio::omni) target_language: &'a str,
    pub(in crate::audio::omni) buffer_size: u64,
    pub(in crate::audio::omni) pre_session_audio_queue_len: usize,
    pub(in crate::audio::omni) pre_session_audio_dropped: u64,
    pub(in crate::audio::omni) echo_guard_enabled: bool,
}

pub(in crate::audio::omni) struct OmniSocketPollResult<S: RealtimeSocket, R: tauri::Runtime = tauri::Wry> {
    pub(in crate::audio::omni) state: OmniSocketEventState<S, R>,
    pub(in crate::audio::omni) skip_tick: bool,
    pub(in crate::audio::omni) socket_reconnected: bool,
    pub(in crate::audio::omni) reconnected_session_update: Option<Value>,
    pub(in crate::audio::omni) stop_worker: bool,
}
